var express = require("express");
var app = express();
// Body parser is used to generate js object of req (which is no longer generated by Express)
var bodyParser = require("body-parser");
app.use(bodyParser.urlencoded({extended : true}));

app.set("view engine", "ejs");

var friends = ["Lorena", "JP", "Luna", "Raul"];


app.get("/", function(req, res){
	res.render("home");
});

app.get("/friends",function(req,res){
	res.render("friends",{friends : friends});
});

app.post("/addfriend", function(req, res){
	// res.send("YOU HAVE REACHED THE POST ROUTE");
	// 	attribute of req.body must match input element's name (which is now at friends.ejs)
	var newfriend = req.body.newfriend;
	friends.push(newfriend);
	res.redirect("/friends");
	
});

app.listen(3000,function(){
	console.log('Server listening to port 3000'); 
});